[tool.poetry]
name = "stellar-sdk"
version = "6.1.0"
description = "The Python Stellar SDK library provides APIs to build transactions and connect to Horizon."
authors = [
    "overcat <4catcode@gmail.com>",
    "Eno <appweb.cn@gmail.com>"
]
maintainers = ["overcat <4catcode@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/StellarCN/py-stellar-base"
repository = "https://github.com/StellarCN/py-stellar-base"
documentation = "https://stellar-sdk.readthedocs.io/"
keywords = [
    "stellar-sdk",
    "stellar",
    "stellar.org",
    "lumens",
    "xlm",
    "blockchain",
    "distributed exchange",
    "cryptocurrency",
    "dex",
    "horizon",
    "sdex",
    "trading"
]
license = "Apache License 2.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/StellarCN/py-stellar-base/issues"

[tool.poetry.dependencies]
python = "^3.6"
PyNaCl = "^1.4.0"
requests = "^2.26.0"
aiohttp = "^3.8.1"
aiohttp-sse-client = "^0.2.1"
stellar-base-sseclient = "^0.0.21"
mnemonic = "^0.20"
toml = "^0.10.2"
typeguard = "^2.13.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-timeout = "^2.0.1"
pytest-asyncio = "^0.16.0"
pytest-httpserver = "^1.0.2"
# currently, mypy cannot run in pypy https://github.com/python/typed_ast/issues/111
mypy = {version = "^0.910", markers = "platform_python_implementation == 'CPython'"}
types-toml = {version = "^0.10.1", markers = "platform_python_implementation == 'CPython'"}
types-requests = {version = "^2.26.0", markers = "platform_python_implementation == 'CPython'"}

[tool.poetry.extras]
docs = ["sphinx", "sphinx-rtd-theme", "sphinx-autodoc-typehints"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
