[tool.poetry]
name = "stellar-sdk"
version = "11.1.0"
description = "The Python Stellar SDK library provides APIs to build transactions and connect to Horizon and Soroban-RPC server."
authors = [
    "overcat <4catcode@gmail.com>",
    "Eno <appweb.cn@gmail.com>"
]
maintainers = ["overcat <4catcode@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/StellarCN/py-stellar-base"
repository = "https://github.com/StellarCN/py-stellar-base"
documentation = "https://stellar-sdk.readthedocs.io/"
keywords = [
    "stellar-sdk",
    "stellar",
    "stellar.org",
    "lumens",
    "xlm",
    "blockchain",
    "distributed exchange",
    "cryptocurrency",
    "dex",
    "horizon",
    "soroban",
    "sdex",
    "trading",
    "soroban",
    "soroban-rpc"
]
license = "Apache License 2.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/StellarCN/py-stellar-base/issues"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
PyNaCl = "^1.4.0"
requests = "^2.26.0"
aiohttp = { version = "^3.9.1", optional = true}
aiohttp-sse-client = { version = "^0.2.1", optional = true}
mnemonic = "^0.20"
toml = "^0.10.2"
pydantic = "^2.5.2"
xdrlib3 = "^0.1.1"
requests-sse = "^0.3.0"

[tool.poetry.extras]
aiohttp = ["aiohttp", "aiohttp-sse-client"]

[tool.poetry.dev-dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
pytest-timeout = "^2.3.1"
pytest-asyncio = "^0.24.0"
pytest-httpserver = "^1.1.0"
types-toml = {version = "^0.10.8", markers = "platform_python_implementation == 'CPython'"}
types-requests = {version = "^2.32.0", markers = "platform_python_implementation == 'CPython'"}
autoflake = "2.3.1"
isort = "5.13.2"
black = "24.8.0"
# currently, mypy cannot run in pypy https://github.com/python/typed_ast/issues/111
mypy = {version = "1.11.2", markers = "platform_python_implementation == 'CPython'"}
requests-mock = "^1.12.1"
aioresponses = {git = "https://github.com/pnuckowski/aioresponses.git"}

[tool.mypy]
show_error_codes = true
ignore_missing_imports = true
warn_unused_configs = true
no_implicit_optional = false

[tool.coverage.run]
source = [
    "stellar_sdk/",
    "tests/"
]

[tool.coverage.report]
omit = [
    "stellar_sdk/xdr/*",
]
exclude_lines = [
    "pragma: no cover",
    "raise AssertionError",
    "raise NotImplementedError",
    "return NotImplemented",
    "def __repr__",
    "def __str__",
    "if self\\.debug",
    "if 0:",
    "if __name__ == .__main__.:",
    "pass"
]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
